--liquibase formatted sql

--changeset truemabadi:1
CREATE TABLE IF NOT EXISTS notifications
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    message     TEXT NOT NULL,
    data_time   TIMESTAMP NOT NULL
);